name: Docs

on:
  push:
    branches:
      - master

jobs:
  docs:
    container:
      image: okapilib/ubuntu-base:18.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v1.0.0

      - name: Update Submodules
        run: git submodule update --init --recursive

      - name: Build Docs
        run: ./run_doxygen.sh

      - name: Publish Docs
        run: |
          rm -rf /tmp/html
          cp -r html /tmp/
          git config --local user.name "OkapiLibBot"
          git config --local user.email "octogonapus@okapilib.org"
          git checkout gh-pages
          rm -rf *
          cp -r /tmp/html/* .
          git add .
          git commit -m "Publishing GitHub Pages"

      - name: Push changes
        uses: ad-m/github-push-action@master
        if: ${{ success() && github.ref == "master" }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
